// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcuuuhznqkmatincvnoo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjdXV1aHpucWttYXRpbmN2bm9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NjA0OTMsImV4cCI6MjA2ODUzNjQ5M30.t9qAJg-_x78U1ihUI2GKVkCaLXrWcfPzOErd1bzL6-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});